version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/app
hooks:
  BeforeInstall:
    - location: aws/before_install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: aws/after_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: aws/application_start.sh
      timeout: 300
      runas: ubuntu
